### PR TITLE
Change the structure of the entity

### PR DESCRIPTION
**Pull request by coleng2**
Made a new bank collection package and user management class

### CODE REVIEW

**Review by jinyeong617 — COMMENTED** [review]
The Account class looks well-structured, utilizing constructor overloading to provide flexibility in object instantiation. It's good to see encapsulation through private fields and appropriate getter and setter methods for balance and foreign currencies.

**Review by tfsolo — COMMENTED** [review]
- Consider adding more comments for complex logic.
- Ensure proper Javadoc comments for all methods.
-Include test cases for class functionality.
- Implement exception handling, especially for user input and external systems.
- Review and maintain consistency in naming conventions.Consider adding more - comments for complex logic.

**Comment by coleng2** [comment]
> * Consider adding more comments for complex logic.
> * Ensure proper Javadoc comments for all methods.
>   -Include test cases for class functionality.
> * Implement exception handling, especially for user input and external systems.
> * Review and maintain consistency in naming conventions.Consider adding more - comments for complex logic.

erased few duplicated suggestions

**Review by dodorlee1210 — APPROVED** [review]
+ Different banks with sufficient methods for transactions added. 
- Would help if there were comments or javadoc to explain each method.

**Pull request merged**
